# Generated by Django 6.0.6 on 2026-07-01 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The website URL being audited', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current state of this audit job', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Overall SEO score out of 100 (null until audit completes)', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Populated only if status is 'failed' — stores what went wrong", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the audit was requested')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the audit finished (success or failure)', null=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(help_text="Short identifier, e.g. 'title_tag', 'meta_description', 'h1_heading'", max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('on_page', 'On-Page'), ('performance', 'Performance'), ('social', 'Social')], default='on_page', max_length=20)),
                ('severity', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], default='pass', max_length=10)),
                ('passed', models.BooleanField(default=False, help_text='True if this check passed, False otherwise')),
                ('message', models.CharField(help_text="Human-readable explanation, e.g. 'Title is 72 characters — too long'", max_length=500)),
                ('details', models.JSONField(blank=True, help_text='Optional structured extra data, e.g. list of image URLs missing alt text', null=True)),
                ('audit', models.ForeignKey(help_text='The parent audit this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audits.audit')),
            ],
            options={
                'verbose_name': 'Audit Result',
                'verbose_name_plural': 'Audit Results',
                'ordering': ['category', 'check_name'],
            },
        ),
    ]
