# Generated by Django 6.0.6 on 2026-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='error_type',
            field=models.CharField(blank=True, help_text="Machine-readable error category, e.g. 'timeout', 'dns_error'", max_length=30, null=True),
        ),
    ]
