# Generated by Django 6.0.6 on 2026-07-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_audit_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='affected_element',
            field=models.CharField(blank=True, help_text='The specific tag/element this check refers to, e.g. \'<title>\' or \'img[src="/logo.png"]\'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='recommendation',
            field=models.CharField(blank=True, help_text='Actionable suggestion for fixing this issue, shown only when severity != pass', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('on_page', 'On-Page'), ('performance', 'Performance'), ('social', 'Social'), ('structured_data', 'Structured Data'), ('accessibility', 'Accessibility')], default='on_page', max_length=20),
        ),
    ]
