# Generated by Django 6.0.6 on 2026-07-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auditresult_affected_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='content_seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Content SEO category score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='full_report',
            field=models.JSONField(blank=True, help_text='Complete structured report from scraper.scoring.build_seo_report() — keyword analysis, content quality, link analysis, mobile, security, and performance data, all in one place.', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Performance category score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='technical_seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Technical SEO category score (0-100)', null=True),
        ),
    ]
