# Generated by Django 6.0.6 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_audit_content_seo_score_audit_full_report_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['-created_at'], name='audit_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['-score'], name='audit_score_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['url'], name='audit_url_idx'),
        ),
    ]